from models import *
from datetime import *

setup_all()
create_all()

champions = [["""Ahri""","""The Nine-Tailed Fox""",date(2011, 10, 14),"""AhriSquare.png""","""ahri.jpg"""],
        ["""Akali""","""The Fist of the Shadow""",date(2010, 5, 11),"""AkaliSquare.png""","""akali.jpg"""],
        ["""Alistar""","""The Minotaur""",date(2009, 2, 21),"""AlistarSquare.png""","""alistar.jpg"""],
        ["""Amumu""","""The Sad Mummy""",date(2009, 6, 26),"""AmumuSquare.png""","""amumu.jpg"""],
        ["""Anivia""","""The Cryophoenix""",date(2009, 6, 10),"""AniviaSquare.png""","""anivia.jpg"""],
        ["""Annie""","""The Dark Child""",date(2009, 2, 21),"""AnnieSquare.png""","""annie.jpg"""],
        ["""Ashe""","""The Frost Archer""",date(2009, 2, 21),"""AsheSquare.png""","""ashe.jpg"""],
        ["""Blitzcrank""","""The Great Steam Golem""",date(2009, 8, 2),"""BlitzcrankSquare.png""","""blitzcrank.jpg"""],
        ["""Brand""","""The Burning Vengeance""",date(2011, 8, 12),"""BrandSquare.png""","""brand.jpg"""],
        ["""Caitlyn""","""The Sheriff of Piltover""",date(2011, 1, 4),"""CaitlynSquare.png""","""caitlyn.jpg"""],
        ["""Cassiopeia""","""The Serpent's Embrace""",date(2010, 12, 14),"""CassiopeiaSquare.png""","""cassiepeia.jpg"""],
        ["""Cho'Gath""","""The Terror of the Void""",date(2009, 6, 26),"""ChogathSquare.png""","""chogath.jpg"""],
        ["""Corki""","""The Daring Bombardier""",date(2009, 9, 19),"""CorkiSquare.png""","""corki.jpg"""],
        ["""Darius""","""The Hand of Noxus""",date(2012, 5, 23),"""DariusSquare.png""","""darius.jpg"""],
        ["""Diana""","""The Scorn of the Moon""",date(2012, 8, 7),"""DianaSquare.png""","""diana.jpg"""],
        ["""Dr. Mundo""","""The Madman of Zaun""",date(2009, 9, 2),"""DrMundoSquare.png""","""drmundo.jpg"""],
        ["""Draven""","""The Glorious Executioner""",date(2012, 6, 6),"""DravenSquare.png""","""draven.jpg"""],
        ["""Evelynn""","""The Widowmaker""",date(2009, 5, 1),"""EvelynnSquare.png""","""evelynn.jpg"""],
        ["""Ezreal""","""The Prodigal Explorer""",date(2010, 3, 16),"""EzrealSquare.png""","""ezreal.jpg"""],
        ["""Fiddlesticks""","""The Harbinger of Doom""",date(2009, 2, 21),"""FiddlesticksSquare.png""","""fiddlesticks.jpg"""],
        ["""Fiora""","""The Grand Duelist""",date(2012, 2, 29),"""FioraSquare.png""","""fiora.jpg"""],
        ["""Fizz""","""The Tidal Trickster""",date(2011, 11, 15),"""FizzSquare.png""","""fizz.jpg"""],
        ["""Galio""","""The Sentinel's Sorrow""",date(2010, 8, 10),"""GalioSquare.png""","""galio.jpg"""],
        ["""Gangplank""","""The Saltwater Scourge""",date(2009, 8, 19),"""GangplankSquare.png""","""gangplank.jpg"""],
        ["""Garen""","""The Might of Demacia""",date(2010, 4, 27),"""GarenSquare.png""","""garen.jpg"""],
        ["""Gragas""","""The Rabble Rouser""",date(2010, 2, 2),"""GragasSquare.png""","""gragas.jpg"""],
        ["""Graves""","""The Outlaw""",date(2011, 10, 19),"""GravesSquare.png""","""graves.jpg"""],
        ["""Hecarim""","""The Shadow of War""",date(2012, 4, 18),"""HecarimSquare.png""","""hecarim.jpg"""],
        ["""Heimerdinger""","""The Revered Inventor""",date(2009, 10, 10),"""HeimerdingerSquare.png""","""heimerdinger.jpg"""],
        ["""Irelia""","""The Will of the Blades""",date(2010, 11, 16),"""IreliaSquare.png""","""irelia.png"""],
        ["""Janna""","""The Storm's Fury""",date(2009, 9, 2),"""JannaSquare.png""","""janna.jpg"""],
        ["""Jarvan IV""","""The Exemplar of Demacia""",date(2011, 3, 1),"""JarvanIVSquare.png""","""jarvanIV.jpg"""],
        ["""Jax""","""The Grandmaster at Arms""",date(2009, 2, 21),"""JaxSquare.png""","""jax.jpg"""],
        ["""Jayce""","""The Defender of Tomorrow""",date(2012, 7, 7),"""JayceSquare.png""","""jayce.jpg"""],
        ["""Karma""","""The Enlightened One""",date(2011, 2, 1),"""KarmaSquare.png""","""karma.jpg"""],
        ["""Karthus""","""The Deathsinger""",date(2009, 6, 12),"""KarthusSquare.png""","""karthus.jpg"""],
        ["""Kassadin""","""The Void Walker""",date(2009, 8, 7),"""KassadinSquare.png""","""kassadin.jpg"""],
        ["""Katarina""","""The Sinister Blade""",date(2009, 9, 19),"""KatarinaSquare.png""","""katarina.jpg"""],
        ["""Kayle""","""The Judicator""",date(2009, 2, 21),"""KayleSquare.png""","""kayle.jpg"""],
        ["""Kennen""","""The Heart of the Tempest""",date(2008, 4, 8),"""KennenSquare.png""","""kennen.jpg"""],
        ["""Kha'Zix""", """The Voidreaver""", date(2012, 9, 27), """Kha'ZixSquare.png""", """khazix.jpg"""],
        ["""Kog'Maw""","""The Mouth of the Abyss""",date(2010, 6, 24),"""KogMawSquare.png""","""kogmaw.jpg"""],
        ["""LeBlanc""","""The Deceiver""",date(2010, 11, 20),"""LeBlancSquare.png""","""leblanc.jpg"""],
        ["""Lee Sin""","""The Blind Monk""",date(2011, 4, 1),"""LeeSinSquare.png""","""leesin.jpg"""],
        ["""Leona""","""The Radiant Dawn""",date(2011, 7, 13),"""LeonaSquare.png""","""leona.jpg"""],
        ["""Lulu""","""The Fae Sorceress""",date(2012, 3, 20),"""LuluSquare.png""","""lulu.jpg"""],
        ["""Lux""","""The Lady of Luminosity""",date(2010, 10, 19),"""LuxSquare.png""","""lux.jpg"""],
        ["""Malphite""","""The Shard of the Monolith""",date(2009, 9, 2),"""MalphiteSquare.png""","""malphite.jpg"""],
        ["""Malzahar""","""The Prophet of the Void""",date(2010, 6, 1),"""MalzaharSquare.png""","""malzahar.jpg"""],
        ["""Maokai""","""The Twisted Treant""",date(2011, 2, 16),"""MaokaiSquare.png""","""maokai.jpg"""],
        ["""Master Yi""","""The Wuju Bladesman""",date(2009, 2, 21),"""MasterYiSquare.png""","""masteryi.jpg"""],
        ["""Miss Fortune""","""The Bounty Hunter""",date(2010, 10, 8),"""MissFortuneSquare.png""","""missfortune.jpg"""],
        ["""Mordekaiser""","""The Master of Metal""",date(2010, 2, 24),"""MordekaiserSquare.png""","""mordekaiser.jpg"""],
        ["""Morgana""","""The Fallen Angel""",date(2009, 2, 21),"""MorganaSquare.png""","""morgana.jpg"""],
        ["""Nasus""","""The Curator of the Sands""",date(2009, 10, 1),"""NasusSquare.png""","""nasus.jpg"""],
        ["""Nautilus""","""The Titan of the Depths""",date(2012, 2, 14),"""NautilusSquare.png""","""nautilus.jpg"""],
        ["""Nidalee""","""The Bestial Huntress""",date(2009, 12, 17),"""NidaleeSquare.png""","""nidalee.jpg"""],
        ["""Nocturne""","""The Eternal Nightmare""",date(2011, 3, 15),"""NocturneSquare.png""","""nocturne.jpg"""],
        ["""Nunu""","""The Yeti Rider""",date(2009, 2, 21),"""NunuSquare.png""","""nunu.jpg"""],
        ["""Olaf""","""The Berserker""",date(2010, 6, 9),"""OlafSquare.png""","""olaf.jpg"""],
        ["""Orianna""","""The Lady of Clockwork""",date(2011, 6, 1),"""OriannaSquare.png""","""orianna.jpg"""],
        ["""Pantheon""","""The Artisan of War""",date(2010, 2, 2),"""PantheonSquare.png""","""pantheon.jpg"""],
        ["""Poppy""","""The Iron Ambassador""",date(2010, 1, 13),"""PoppySquare.png""","""poppy.jpg"""],
        ["""Rammus""","""The Armordillo""",date(2010, 7, 10),"""RammusSquare.png""","""rammus.jpg"""],
        ["""Renekton""","""The Butcher of the Sands""",date(2011, 2, 17),"""RenektonSquare.png""","""renekton.jpg"""],
        ["""Rengar""", """The Pridestalker""", date(2012, 9, 21), """RengarSquare.png""", """rengar.jpg"""],
        ["""Riven""","""The Exile""",date(2011, 9, 14),"""RivenSquare.png""","""riven.jpg"""],
        ["""Rumble""","""The Mechanized Menace""",date(2011, 4, 26),"""RumbleSquare.png""","""rumble.jpg"""],
        ["""Ryze""","""The Rogue Mage""",date(2009, 2, 21),"""RyzeSquare.png""","""ryze.jpg"""],
        ["""Sejuani""","""The Winter's Wrath""",date(2012, 1, 17),"""SejuaniSquare.png""","""sejuani.jpg"""],
        ["""Shaco""","""The Demon Jester""",date(2009, 2, 21),"""ShacoSquare.png""","""shaco.jpg"""],
        ["""Shen""","""The Eye of Twilight""",date(2010, 3, 24),"""ShenSquare.png""","""shen.jpg"""],
        ["""Shyvana""","""The Half-Dragon""",date(2011, 11, 1),"""ShyvanaSquare.png""","""shyvana.jpg"""],
        ["""Singed""","""The Mad Chemist""",date(2009, 4, 18),"""SingedSquare.png""","""singed.jpg"""],
        ["""Sion""","""The Undead Champion""",date(2009, 2, 21),"""SionSquare.png""","""sion.jpg"""],
        ["""Sivir""","""The Battle Mistress""",date(2009, 2, 21),"""SivirSquare.png""","""sivir.jpg"""],
        ["""Skarner""","""The Crystal Vanguard""",date(2011, 8, 9),"""SkarnerSquare.png""","""skarner.jpg"""],
        ["""Sona""","""The Maven of the Strings""",date(2010, 9, 20),"""SonaSquare.png""","""sona.jpg"""],
        ["""Soraka""","""The Starchild""",date(2009, 2, 21),"""SorakaSquare.png""","""soraka.jpg"""],
        ["""Swain""","""The Master Tactician""",date(2010, 10, 5),"""SwainSquare.png""","""swain.jpg"""],
        ["""Talon""","""The Blade's Shadow""",date(2011, 8, 24),"""TalonSquare.png""","""talon.jpg"""],
        ["""Taric""","""The Gem Knight""",date(2009, 8, 19),"""TaricSquare.png""","""taric.jpg"""],
        ["""Teemo""","""The Swift Scout""",date(2009, 2, 21),"""TeemoSquare.png""","""teemo.jpg"""],
        ["""Tristana""","""The Megling Gunner""",date(2009, 2, 21),"""TristanaSquare.png""","""tristana.jpg"""],
        ["""Trundle""","""The Cursed Troll""",date(2010, 12, 1),"""TrundleSquare.png""","""trundle.jpg"""],
        ["""Tryndamere""","""The Barbarian King""",date(2009, 5, 1),"""TryndamereSquare.png""","""trydamere.jpg"""],
        ["""Twisted Fate""","""The Card Master""",date(2009, 2, 21),"""TwistedFateSquare.png""","""twistedfate.jpg"""],
        ["""Twitch""","""The Plague Rat""",date(2009, 5, 1),"""TwitchSquare.png""","""twitch.jpg"""],
        ["""Udyr""","""The Animal Spirit""",date(2009, 12, 2),"""UdyrSquare.png""","""udyr.jpg"""],
        ["""Urgot""","""The Headsman's Pride""",date(2012, 8, 24),"""UrgotSquare.png""","""urgot.jpg"""],
        ["""Varus""","""The Arrow of Retribution""",date(2012, 5, 8),"""VarusSquare.png""","""varus.jpg"""],
        ["""Vayne""","""The Night Hunter""",date(2011, 5, 10),"""VayneSquare.png""","""vayne.jpg"""],
        ["""Veigar""","""The Tiny Master of Evil""",date(2009, 7, 24),"""VeigarSquare.png""","""veigar.jpg"""],
        ["""Viktor""","""The Machine Herald""",date(2011, 12, 29),"""ViktorSquare.png""","""viktor.jpg"""],
        ["""Vladimir""","""The Crimson Reaper""",date(2010, 7, 27),"""VladimirSquare.png""","""vladimir.jpg"""],
        ["""Volibear""","""The Thunder's Roar""",date(2011, 11, 29),"""VolibearSquare.png""","""volibear.jpg"""],
        ["""Warwick""","""The Blood Hunter""",date(2009, 2, 21),"""WarwickSquare.png""","""warwick.jpg"""],
        ["""Wukong""","""The Monkey King""",date(2011, 7, 26),"""WukongSquare.png""","""wukong.jpg"""],
        ["""Xerath""","""The Magus Ascendant""",date(2011, 8, 5),"""XerathSquare.png""","""xerath.jpg"""],
        ["""XinZhao""","""The Seneschal of Demacia""",date(2010, 7, 13),"""XinZhaoSquare.png""","""xinzhao.jpg"""],
        ["""Yorick""","""The Gravedigger""",date(2011, 6, 22),"""YorickSquare.png""","""yorick.jpg"""],
        ["""Ziggs""","""The Hexplosives Expert""",date(2012, 2, 1),"""ZiggsSquare.png""","""ziggs.jpg"""],
        ["""Zilean""","""The Chronokeeper""",date(2009, 4, 18),"""ZileanSquare.png""","""zilean.jpg"""],
        ["""Zyra""","""The Rise of the Thorns""",date(2012, 7, 24),"""ZyraSquare.png""","""zyra.jpg"""],
    ]


for champion in champions:
	champ_data = Champion(name = champion[0],
                          riot_name = champion[0].replace(' ', '').replace("'", "").lower(),
						  title = champion[1],
						  rel_date = champion[2],
						  thumbnail = champion[3],
						  splash_art = champion[4])



side1 = Side(color=1)
side2 = Side(color=2)

session.commit()
